/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Visual;

import Datos.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jinjo
 */
public class Informacion extends javax.swing.JDialog {
         DefaultTableModel modeloNumero;
         DefaultTableModel modeloCorreo;
         static Nodo<Contacto> contacto;
    /**
     * Creates new form Informacion
     */
    
    public Informacion(java.awt.Frame parent, boolean modal, Nodo<Contacto> contacto) {
        super(parent, modal);
        initComponents();
        this.contacto=contacto;
        String[] cabecera={"Numero" };
        String[][] datos={};
        modeloNumero=new DefaultTableModel(datos,cabecera);
        jTableNumeros.setModel(modeloNumero);
        cabecera[0]="Correos";
        modeloCorreo=new DefaultTableModel(datos,cabecera);
        jTableCorreos.setModel(modeloCorreo);
        actualizarCorreos();
        actualizarNumeros();
        jTextField1.setText(contacto.getInfo().getNombre());
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNumeros = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableCorreos = new javax.swing.JTable();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldCorreo = new javax.swing.JTextField();
        jButtonAgregarNumero = new javax.swing.JButton();
        jButtonBorrarNumero = new javax.swing.JButton();
        jButtonNuevoCorreo = new javax.swing.JButton();
        jButtonBorrarCorreo = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTableNumeros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableNumeros);

        jScrollPane1.setViewportView(jScrollPane2);

        jTableCorreos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTableCorreos);

        jScrollPane3.setViewportView(jScrollPane4);

        jButtonAgregarNumero.setText("Agregar Numero");
        jButtonAgregarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarNumeroActionPerformed(evt);
            }
        });

        jButtonBorrarNumero.setText("Borrar Numero");
        jButtonBorrarNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarNumeroActionPerformed(evt);
            }
        });

        jButtonNuevoCorreo.setText("Agregar Correo");
        jButtonNuevoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoCorreoActionPerformed(evt);
            }
        });

        jButtonBorrarCorreo.setText("Borrar Correo");
        jButtonBorrarCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarCorreoActionPerformed(evt);
            }
        });

        jButton5.setText("Salir");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre:");

        jButton1.setText("Cambiar nombre");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                            .addComponent(jButtonAgregarNumero)
                            .addComponent(jButtonBorrarNumero))
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonBorrarCorreo)
                            .addComponent(jButtonNuevoCorreo)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgregarNumero)
                    .addComponent(jButtonNuevoCorreo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrarNumero)
                    .addComponent(jButtonBorrarCorreo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButtonAgregarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarNumeroActionPerformed
      if(jTextFieldNumero.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Introduzca un numero de telefono");
      }else{
          contacto.getInfo().getTelefonos().insertar(jTextFieldNumero.getText());
          jTextFieldNumero.setText("");
          actualizarNumeros();
      }
    }//GEN-LAST:event_jButtonAgregarNumeroActionPerformed

    private void jButtonNuevoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoCorreoActionPerformed
       if(jTextFieldCorreo.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Introduzca una Direccion de Correo");
      }else{
          contacto.getInfo().getEmails().insertar(jTextFieldCorreo.getText());
          jTextFieldCorreo.setText("");
          actualizarCorreos();
      }
    }//GEN-LAST:event_jButtonNuevoCorreoActionPerformed

    private void jButtonBorrarNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarNumeroActionPerformed
try{    
        int index=jTableNumeros.getSelectedRow();
        if(index==-1){
            throw new ArrayIndexOutOfBoundsException();
        }
        System.out.println("indice"+index);
          if(index==0){
              contacto.getInfo().getTelefonos().borrarInicio();
          }else{
              if(index==modeloNumero.getRowCount()){
                  contacto.getInfo().getTelefonos().borrarFinal();
              }else{
                  contacto.getInfo().getTelefonos().borrar(index);
              }
          }      
                actualizarNumeros();
                }
                catch(ArrayIndexOutOfBoundsException ex){
                    JOptionPane.showMessageDialog(null, "Seleccione un numero para borrar");
                }      
    }//GEN-LAST:event_jButtonBorrarNumeroActionPerformed

    private void jButtonBorrarCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarCorreoActionPerformed
        try{
        int index=jTableCorreos.getSelectedRow();
        if(index==-1){
            throw new ArrayIndexOutOfBoundsException();
        }
          if(index==0){
              contacto.getInfo().getEmails().borrarInicio();
          }else{
              if(index==modeloCorreo.getRowCount()){
                  contacto.getInfo().getEmails().borrarFinal();
              }else{
                  contacto.getInfo().getEmails().borrar(index);
              }
          }      
                actualizarCorreos();
                }
                catch(ArrayIndexOutOfBoundsException ex){
                    JOptionPane.showMessageDialog(null, "Seleccione un correo para borrar");
                }
    }//GEN-LAST:event_jButtonBorrarCorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(jTextField1.getText().equals("")){
          JOptionPane.showMessageDialog(null, "Nombre Invalido");
      }else{
        contacto.getInfo().setNombre(jTextField1.getText());
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void actualizarCorreos(){
        for (int i = modeloCorreo.getRowCount()-1; i >=0; i--) {
            modeloCorreo.removeRow(i);
            
        }
        Nodo<String> aux= contacto.getInfo().getEmails().getInicio();
       
        while(aux!=null){
            String datos[]={aux.getInfo()};
            System.out.println(datos[0]);
            modeloCorreo.insertRow(modeloCorreo.getRowCount(), datos);
            aux=aux.getLiga();
        }
       
    }
    
     private void actualizarNumeros(){
        for (int i = modeloNumero.getRowCount()-1; i >=0; i--) {
            modeloNumero.removeRow(i);
            
        }
        Nodo<String> aux= contacto.getInfo().getTelefonos().getInicio();
       
        while(aux!=null){
            String datos[]={aux.getInfo()};
            modeloNumero.insertRow(modeloNumero.getRowCount(), datos);
            aux=aux.getLiga();
        }
       
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Informacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Informacion dialog = new Informacion(new javax.swing.JFrame(), true, contacto);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButtonAgregarNumero;
    private javax.swing.JButton jButtonBorrarCorreo;
    private javax.swing.JButton jButtonBorrarNumero;
    private javax.swing.JButton jButtonNuevoCorreo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableCorreos;
    private javax.swing.JTable jTableNumeros;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCorreo;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
